<?php

namespace Database\Seeders;

use App\Models\Properti;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        $propertis = [
            [
                'nama' => 'Cluster Melati Indah',
                'tipe' => 'Rumah Subsidi',
                'subsidi' => true,
                'harga' => 185000000,
                'lokasi' => 'Jl. Raya Pasar Kemis',
                'kota' => 'Tangerang',
                'developer' => 'PT Bangun Sejahtera',
                'luas_tanah' => 60,
                'luas_bangunan' => 36,
                'kamar_tidur' => 2,
                'kamar_mandi' => 1,
                'deskripsi' => 'Rumah subsidi bersubsidi dengan akses tol dan dekat dengan pusat perbelanjaan. Lingkungan asri dan aman.',
                'gambar' => 'https://placehold.co/600x400/22c55e/ffffff?text=Cluster+Melati',
                'status' => 'tersedia',
            ],
            [
                'nama' => 'Griya Nusa Permai',
                'tipe' => 'Rumah Subsidi',
                'subsidi' => true,
                'harga' => 162000000,
                'lokasi' => 'Jl. Raya Cikupa',
                'kota' => 'Tangerang',
                'developer' => 'PT Nusa Indah',
                'luas_tanah' => 54,
                'luas_bangunan' => 30,
                'kamar_tidur' => 2,
                'kamar_mandi' => 1,
                'deskripsi' => 'Perumahan subsidi terjangkau dekat kawasan industri. Cocok untuk pekerja pabrik dan karyawan.',
                'gambar' => 'https://placehold.co/600x400/16a34a/ffffff?text=Griya+Nusa',
                'status' => 'tersedia',
            ],
            [
                'nama' => 'Bukit Cemara Asri',
                'tipe' => 'Rumah Subsidi',
                'subsidi' => true,
                'harga' => 196000000,
                'lokasi' => 'Jl. Raya Dramaga',
                'kota' => 'Bogor',
                'developer' => 'PT Cemara Sejahtera',
                'luas_tanah' => 72,
                'luas_bangunan' => 45,
                'kamar_tidur' => 3,
                'kamar_mandi' => 1,
                'deskripsi' => 'Perumahan dengan view pegunungan, udara sejuk, cocok untuk keluarga. Akses 30 menit ke kota Bogor.',
                'gambar' => 'https://placehold.co/600x400/15803d/ffffff?text=Bukit+Cemara',
                'status' => 'tersedia',
            ],
            [
                'nama' => 'Permata Mutiara Residence',
                'tipe' => 'Rumah Subsidi',
                'subsidi' => true,
                'harga' => 178000000,
                'lokasi' => 'Jl. Raya Serpong',
                'kota' => 'Tangerang Selatan',
                'developer' => 'PT Mutiara Group',
                'luas_tanah' => 60,
                'luas_bangunan' => 36,
                'kamar_tidur' => 2,
                'kamar_mandi' => 1,
                'deskripsi' => 'Lokasi strategis dekat BSD City. Lingkungan modern dengan fasilitas lengkap.',
                'gambar' => 'https://placehold.co/600x400/166534/ffffff?text=Permata+Mutiara',
                'status' => 'tersedia',
            ],
            [
                'nama' => 'Gardenia Residence',
                'tipe' => 'Apartemen Subsidi',
                'subsidi' => true,
                'harga' => 150000000,
                'lokasi' => 'Jl. Raya Kalimalang',
                'kota' => 'Bekasi',
                'developer' => 'PT Gardenia Developer',
                'luas_tanah' => 0,
                'luas_bangunan' => 24,
                'kamar_tidur' => 1,
                'kamar_mandi' => 1,
                'deskripsi' => 'Apartemen subsidi cocok untuk milenial. Dekat stasiun KRL, akses mudah ke Jakarta.',
                'gambar' => 'https://placehold.co/600x400/14532d/ffffff?text=Gardenia',
                'status' => 'tersedia',
            ],
            [
                'nama' => 'Purui Indah City',
                'tipe' => 'Rumah Subsidi',
                'subsidi' => true,
                'harga' => 193000000,
                'lokasi' => 'Jl. Purui Indah',
                'kota' => 'Depok',
                'developer' => 'PT Indah Bangun',
                'luas_tanah' => 66,
                'luas_bangunan' => 40,
                'kamar_tidur' => 2,
                'kamar_mandi' => 1,
                'deskripsi' => 'Lokasi strategis dekat UI dan akses tol. Cocok untuk keluarga muda.',
                'gambar' => 'https://placehold.co/600x400/0f3b1f/ffffff?text=Purui+Indah',
                'status' => 'tersedia',
            ],
            [
                'nama' => 'Kavling Griya Sejahtera',
                'tipe' => 'Rumah Non-Subsidi',
                'subsidi' => false,
                'harga' => 350000000,
                'lokasi' => 'Jl. Alternatif Sentul',
                'kota' => 'Bogor',
                'developer' => 'PT Griya Sejahtera',
                'luas_tanah' => 72,
                'luas_bangunan' => 50,
                'kamar_tidur' => 3,
                'kamar_mandi' => 2,
                'deskripsi' => 'Perumahan premium dengan view gunung. Fasilitas lengkap ada kolam renang dan taman.',
                'gambar' => 'https://placehold.co/600x400/0c2d1b/ffffff?text=Griya+Sejahtera',
                'status' => 'tersedia',
            ],
            [
                'nama' => 'The Rosewood Apartment',
                'tipe' => 'Apartemen Non-Subsidi',
                'subsidi' => false,
                'harga' => 450000000,
                'lokasi' => 'Jl. TB Simatupang',
                'kota' => 'Jakarta Selatan',
                'developer' => 'PT Rosewood Suites',
                'luas_tanah' => 0,
                'luas_bangunan' => 42,
                'kamar_tidur' => 2,
                'kamar_mandi' => 1,
                'deskripsi' => 'Apartemen mewah di pusat bisnis Jakarta. Akses tol, mall, dan RS di sekitar.',
                'gambar' => 'https://placehold.co/600x400/081f11/ffffff?text=Rosewood',
                'status' => 'tersedia',
            ],
        ];

        foreach ($propertis as $properti) {
            Properti::create($properti);
        }
    }
}